
export interface MindMapNode {
  id: string;
  text: string; // Agent C manages this
  detail?: string; // Detailed description for the node
  children: MindMapNode[];
  isExpanded?: boolean;
}

export interface Project {
  id: string;
  name: string;
  mindMap: MindMapNode;
  noteA: string; // The linear log (User inputs + choices). Read-only for user.
  noteB: string; // The detailed spec (Generated by Agent D). Read-only for user.
  historyStack: string[]; // For specific 15-step undo/redo (stores JSON strings)
  lastModified: number;
}

export interface AgentPrompts {
  programmer: string; // Agent A
  product: string;    // Agent B
  mapper: string;     // Agent C
  summarizer: string; // Agent D
  promptEngineer: string; // Agent E
  critic: string;     // Agent F
}

export interface AISettings {
  apiKey: string;
  baseUrl: string;
  model: string;
  agentPrompts: AgentPrompts;
}

export interface DeepQuery {
  id: string;
  question: string;
  agent: 'Programmer' | 'Product'; // Agent A or B
  options: string[];
  allowCustom: boolean;
  selectedOption?: string;
  customAnswer?: string;
}

export interface Suggestion {
  id: string;
  text: string;
  agent: 'Programmer' | 'Product'; // Agent A or B
  accepted: boolean;
}

export interface Criticism {
  id: string;
  text: string;
}

export interface AIAnalysisResult {
  mindMap: MindMapNode;
  noteB: string;
  deepQueries: DeepQuery[];
  suggestions: Suggestion[];
  criticisms: Criticism[];
}
